name       : haskell-random
version    : 1.1
release    : 6
source     :
    - http://hackage.haskell.org/package/random-1.1/random-1.1.tar.gz : b718a41057e25a3a71df693ab0fe2263d492e759679b3c2fea6ea33b171d3a5a
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a basic random number generation library, including
    the ability to split random number generators.
description: |
    This package provides a basic random number generation library, including the ability to split random number generators.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
