name       : haskell-random
version    : 1.2.1.1
release    : 8
source     :
    - https://hackage.haskell.org/package/random-1.2.1.1/random-1.2.1.1.tar.gz : 3e1272f7ed6a4d7bd1712b90143ec326fee9b225789222379fea20a9c90c9b76
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a basic random number generation library, including the ability to split random number generators.
description: |
    This package provides a basic random number generation library, including the ability to split random number generators.
builddeps  :
    - ghc-devel
    - haskell-splitmix-devel
rundeps    :
    - devel :
        - haskell-splitmix-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
