name       : haskell-random
version    : 1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/random-1.1/random-1.1.tar.gz : b718a41057e25a3a71df693ab0fe2263d492e759679b3c2fea6ea33b171d3a5a
license    : BSD-3-Clause
component  : programming
summary    : This package provides a basic random number generation library, including the ability to split random number generators.
description: |
    This package provides a basic random number generation library, including the ability to split random number generators.
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 random-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/random-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/random-$version/*.a
